Remove duplicate files, improve sync script and project generation CI.
* Explicitly delete shared TFL/TFLM files prior to sync'ing so that stale files are deleted.
 * Added a bazel build to the project generation CI. This catches errors  like http://b/261106859 that were not caught with the Makefile.
 * Manually ran the sync script: `ci/sync_from_upstream_tf.sh` and included the changes as a separate commit (https://github.com/tensorflow/tflite-micro/pull/1606/commits/99c7ff8a5f2907379002603fc13c40f5077f46dc)


Tested:
 * Confirmed that the new bazel build in test_project_generation would have caught http://b/261106859 by uploading commits with the stale files and seeing that the presubmit checks fail with errors like:
```
/usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/_objs/libtflm/0/common.pic.o: previous definition here
/usr/bin/ld.gold: error: bazel-out/k8-fastbuild/bin/_objs/libtflm/1/common.pic.o: multiple definition of 'TfLiteOpaqueDelegateDelete'
/usr/bin/ld.gold: bazel-out/k8-fastbuild/bin/_objs/libtflm/0/common.pic.o: previous definition here
collect2: error: ld returned 1 exit status
Target //:libtflm failed to build
```

BUG=http://b/261106859