build: update python_rules to support Python 3.12 (#2654)
Before, when trying to use to build the project using Bazel, this would result in multiple occurrence of this error:
`AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?`

This error is due to `rules_python` being too old. While building with Python3.12 still result in an error, the new one clearly indicate is mismatch of the TensorFlow version.

Very similar/related: https://github.com/googleapis/gapic-generator-python/pull/1825

BUG=https://github.com/tensorflow/tensorflow/issues/73174