Tensorflow requires 4.2.2 with https://github.com/tensorflow/tensorflow/pull/53363
Without this change, the sync workflow fails with:
```
ERROR: The project you're trying to build requires Bazel 4.2.2 (specified in /tmp/tensorflow/.bazelversion), but it wasn't found in /usr/local/lib/bazel/bin.
```

BUG=fix broken sync from upstream TF